name: CI

on:
  push:
    branches: [ master, develop ]
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    
    - name: Prepare Project
      run: |
        echo '${{ secrets.GOOGLE_SERVICES_JSON_DEBUG }}' > presentation/src/debug/google-services.json
        echo '${{ secrets.GOOGLE_SERVICES_JSON_MK }}' > presentation/src/mk/google-services.json
        mkdir -p presentation/src/release
        echo '${{ secrets.GOOGLE_SERVICES_JSON_RELEASE }}' > presentation/src/release/google-services.json
        echo '${{ secrets.GRADLE_PROPERTIES }}' > gradle.properties
        cp -a locale-example locale
        echo '${{ secrets.TRANSLATIONS_GRADLE }}' > service/translations.gradle

    - name: Static code analysis
      run: |
        ./gradlew checkstyle
        ./gradlew detekt

    - name: Build
      run: 
        ./gradlew assembleRelease
        
    - name: Test
      run: 
        echo "TODO"
